/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aufgabe2;

import java.time.LocalDateTime;
import java.util.Date;
import javafx.util.converter.DateStringConverter;
import javafx.util.converter.LocalDateStringConverter;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.SpinnerDateModel;
import javax.swing.SpinnerListModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.MutableTreeNode;
import javax.swing.tree.TreePath;

/**
 *
 * @author Matthäus
 */
public class Anwendung extends javax.swing.JFrame {

    /**
     * Creates new form Anwendung
     */
    
    public Anwendung() {
        initComponents();
        DefaultMutableTreeNode root = new DefaultMutableTreeNode("Aktivitätenliste");
        DefaultTreeModel dtm = new DefaultTreeModel(root);
        jTree1.setModel(dtm);
        DefaultComboBoxModel dcbm = new DefaultComboBoxModel(Priority.values());
        jComboBox1.setModel(dcbm);
        SpinnerDateModel sdm = new SpinnerDateModel();
        jSpinner1.setModel(sdm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jSpinner1 = new javax.swing.JSpinner();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        hinzufuegen = new javax.swing.JMenu();
        loeschen = new javax.swing.JMenu();
        aendern = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTree1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTree1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTree1);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        hinzufuegen.setText("Hinzufügen");
        hinzufuegen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hinzufuegenMouseClicked(evt);
            }
        });
        jMenuBar1.add(hinzufuegen);

        loeschen.setText("Löschen");
        loeschen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loeschenMouseClicked(evt);
            }
        });
        jMenuBar1.add(loeschen);

        aendern.setText("Ändern");
        aendern.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aendernMouseClicked(evt);
            }
        });
        jMenuBar1.add(aendern);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hinzufuegenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hinzufuegenMouseClicked
        String titel = JOptionPane.showInputDialog(null, "Bezeichnung");
        DefaultMutableTreeNode temp = new DefaultMutableTreeNode(new Aktivitaet(titel));
        
        TreePath tp = jTree1.getSelectionPath();
        DefaultTreeModel dtm = (DefaultTreeModel) jTree1.getModel();
        
        if(tp == null || tp.getParentPath() == null){
            dtm.insertNodeInto(temp, (MutableTreeNode) dtm.getRoot(), dtm.getChildCount(dtm.getRoot()));
        }else{
            dtm.insertNodeInto(temp, (MutableTreeNode) tp.getLastPathComponent(), dtm.getChildCount(tp.getLastPathComponent()));
        }
    }//GEN-LAST:event_hinzufuegenMouseClicked

    private void loeschenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loeschenMouseClicked
        TreePath tp = jTree1.getSelectionPath();
        DefaultTreeModel dtm = (DefaultTreeModel) jTree1.getModel();
        if(tp == null || tp.getParentPath() == null){
        }else{
            dtm.removeNodeFromParent((MutableTreeNode) tp.getLastPathComponent());
            jTextArea1.setText("");
            DefaultComboBoxModel dcbm = (DefaultComboBoxModel) jComboBox1.getModel();
            dcbm.setSelectedItem(Priority.niedrig);
            SpinnerDateModel sdm = (SpinnerDateModel) jSpinner1.getModel();
            sdm.setValue(new Date());
            
        }
    }//GEN-LAST:event_loeschenMouseClicked

    private void aendernMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aendernMouseClicked
        String name = JOptionPane.showInputDialog(null, "Hier eingeben:", "");
        TreePath tp = jTree1.getSelectionPath();
        if(tp == null || tp.getParentPath() == null){
        }else{
            Aktivitaet temp = (Aktivitaet) ((DefaultMutableTreeNode)tp.getLastPathComponent()).getUserObject();
            temp.setName(name);
            jTree1.updateUI();
        }
    }//GEN-LAST:event_aendernMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TreePath tp = jTree1.getSelectionPath();
        if(tp == null || tp.getParentPath() == null){
            
        }else{
            Aktivitaet temp = (Aktivitaet) ((DefaultMutableTreeNode)tp.getLastPathComponent()).getUserObject();
            temp.setBeschreibung(jTextArea1.getText());
            temp.setDatum((Date) jSpinner1.getValue());
            temp.setPriority((Priority) jComboBox1.getSelectedItem());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTree1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree1MouseClicked
        TreePath tp = jTree1.getSelectionPath();
        if(tp == null || tp.getParentPath() == null){
            
        }else{
            Aktivitaet temp = (Aktivitaet) ((DefaultMutableTreeNode)tp.getLastPathComponent()).getUserObject();
            jTextArea1.setText(temp.getBeschreibung());
            DefaultComboBoxModel dcbm = (DefaultComboBoxModel) jComboBox1.getModel();
            dcbm.setSelectedItem(temp.getPriority());
            SpinnerDateModel sdm = (SpinnerDateModel) jSpinner1.getModel();
            sdm.setValue(temp.getDatum());
        }
    }//GEN-LAST:event_jTree1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Anwendung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Anwendung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Anwendung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Anwendung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Anwendung().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu aendern;
    private javax.swing.JMenu hinzufuegen;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTree jTree1;
    private javax.swing.JMenu loeschen;
    // End of variables declaration//GEN-END:variables
}
